language: go
sudo: required
env:
  - DEP_VERSION="0.4.1" SPAMD_NETWORK="unix" SPAMD_ADDRESS="/var/run/spamd.sock" SPAMD_USER="debian-spamd"
  - DEP_VERSION="0.4.1" SPAMD_NETWORK="tcp4" SPAMD_ADDRESS="127.0.0.1:783" SPAMD_USER="debian-spamd"

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  - sudo rm -vf /opt/jdk_switcher/jdk_switcher.sh
  - sudo apt-get update -qq
  - sudo apt-get install spamassassin || /bin/true
  - sudo usermod --shell /bin/bash debian-spamd
  - sudo mkdir -p /var/lib/spamassassin/db
  - sudo chown debian-spamd:debian-spamd /var/lib/spamassassin/db
  - sudo apt-get install -f
  - echo 'ENABLED=1' | sudo tee -a /etc/default/spamassassin
  - echo 'bayes_path /var/lib/spamassassin/db/bayes' | sudo tee -a /etc/spamassassin/local.cf
  - echo 'OPTIONS="--max-children 5 --helper-home-dir=/var/lib/spamassassin --listen=127.0.0.1 --socketpath=/var/run/spamd.sock --socketmode=0777 -d -l -m5"' | sudo tee -a /etc/default/spamassassin
  - tar xjvf examples/data/bayes-db.tar.bz2
  - sudo cp -av ./bayes-db.txt /tmp/bayes-db.txt
  - sudo -u debian-spamd sa-learn -D --restore /tmp/bayes-db.txt
  - sudo service spamassassin start

go:
  - 1.10.x
  - 1.11.x
  - master

install:
  - make get-deps
